project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left: 
      - text: "Home"
        href: "index.qmd"
      - text: "Proposal"
        href: "proposal/Project_Proposal.html"
      - text: "User Guide"
        href: "user_guide.html"

      

format:
  html:
    theme: Lux
    css: styles.css
    toc: true

editor: visual

